name       : gtk-engines
version    : 2.20.2
release    : 1
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gtk-engines/2.20/gtk-engines-2.20.2.tar.bz2 : 15b680abca6c773ecb85253521fa100dd3b8549befeecc7595b10209d62d66b5
license    : LGPL-2.1
summary    : gtk-engines provides a central location for commonly used GTK+ engines.
description: |
    gtk-engines provides a central location for commonly used GTK+ engines. Including Clearlooks, Crus, Glide, HC, Industrial, Lua, Mist, Redmond and Thinice
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(lua-5.1)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
